# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: platform-iot-streams.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 30, 0, "", "platform-iot-streams.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1aplatform-iot-streams.proto"/\n\x02In\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02sn\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t"0\n\x03Out\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02sm\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t"\x07\n\x05\x45mpty2)\n\rDeviceConnect\x12\x18\n\x07Message\x12\x03.In\x1a\x04.Out(\x01\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "platform_iot_streams_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_IN"]._serialized_start = 30
    _globals["_IN"]._serialized_end = 77
    _globals["_OUT"]._serialized_start = 79
    _globals["_OUT"]._serialized_end = 127
    _globals["_EMPTY"]._serialized_start = 129
    _globals["_EMPTY"]._serialized_end = 136
    _globals["_DEVICECONNECT"]._serialized_start = 138
    _globals["_DEVICECONNECT"]._serialized_end = 179
# @@protoc_insertion_point(module_scope)
