# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: terraina.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'terraina.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eterraina.proto\"\xa5\x01\n\rDeviceMessage\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\n\n\x02sn\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t\x12\x1d\n\nproperties\x18\x05 \x03(\x0b\x32\t.Property\x12\x1c\n\x06\x65vents\x18\x06 \x03(\x0b\x32\x0c.DeviceEvent\x12 \n\x08services\x18\x07 \x01(\x0b\x32\x0e.DeviceService\"\xd9\x01\n\x08Property\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1d\n\nproperties\x18\x02 \x03(\x0b\x32\t.Property\x12\x15\n\x0bstringValue\x18\x03 \x01(\tH\x00\x12\x12\n\x08intValue\x18\x04 \x01(\x05H\x00\x12\x14\n\nint64Value\x18\x05 \x01(\x03H\x00\x12\x14\n\nfloatValue\x18\x06 \x01(\x02H\x00\x12\x15\n\x0b\x64oubleValue\x18\x07 \x01(\x01H\x00\x12\x13\n\tboolValue\x18\x08 \x01(\x08H\x00\x12\x14\n\nbytesValue\x18\t \x01(\x0cH\x00\x42\x07\n\x05value\"4\n\x0b\x44\x65viceEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x06params\x18\x02 \x03(\x0b\x32\x07.Params\"B\n\rDeviceService\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x17\n\x06params\x18\x03 \x03(\x0b\x32\x07.Params\"\xd0\x01\n\x06Params\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x06params\x18\x02 \x03(\x0b\x32\x07.Params\x12\x15\n\x0bstringValue\x18\x03 \x01(\tH\x00\x12\x12\n\x08intValue\x18\x04 \x01(\x05H\x00\x12\x14\n\nint64Value\x18\x05 \x01(\x03H\x00\x12\x14\n\nfloatValue\x18\x06 \x01(\x02H\x00\x12\x15\n\x0b\x64oubleValue\x18\x07 \x01(\x01H\x00\x12\x13\n\tboolValue\x18\x08 \x01(\x08H\x00\x12\x14\n\nbytesValue\x18\t \x01(\x0cH\x00\x42\x07\n\x05valueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'terraina_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICEMESSAGE']._serialized_start=19
  _globals['_DEVICEMESSAGE']._serialized_end=184
  _globals['_PROPERTY']._serialized_start=187
  _globals['_PROPERTY']._serialized_end=404
  _globals['_DEVICEEVENT']._serialized_start=406
  _globals['_DEVICEEVENT']._serialized_end=458
  _globals['_DEVICESERVICE']._serialized_start=460
  _globals['_DEVICESERVICE']._serialized_end=526
  _globals['_PARAMS']._serialized_start=529
  _globals['_PARAMS']._serialized_end=737
# @@protoc_insertion_point(module_scope)
